import { withEnglishUS } from "@/lib/i18n/english-regions";
import type { ComparisonId, ComparisonLocale } from './routes';
import type { FactId } from './facts';

export type ComparisonCopy = {
  hubTitle: string; hubIntro: string; eyebrow: string; seoTopic: string;
  buy: string; demo: string; compare: string; decision: string; choose: string;
  table: string; feature: string; features: readonly string[];
  demoTitle: string; demoText: string; offerTitle: string; offerText: string;
  limitations: string; faq: string; related: string; sources: string; disclosure: string;
  checked: string; package: string; priceNote: string; screenshot: string;
  summaries: Record<ComparisonId, string>;
  facts: Record<FactId, string>;
};

export const comparisonCopy: Record<ComparisonLocale, ComparisonCopy> = withEnglishUS({
  en: {
    hubTitle: 'Find the right home for your wedding photos.',
    hubIntro: 'Compare wedding photo sharing options before you choose. See how guest uploads, QR codes, prices and storage work with WhatsApp, Google Drive, Google Photos and dedicated wedding galleries.',
    eyebrow: 'Wedding photo sharing, compared', seoTopic: 'Wedding photo sharing',
    buy: 'Create our gallery · €35', demo: 'Try the guest demo', compare: 'See the comparison',
    decision: 'Which fits your wedding?', choose: 'Choose', table: 'The details that matter on the day', feature: 'For your wedding',
    features: ['Guest uploads', 'Guest account', 'Photos & videos', 'Downloads', 'Storage & upload window', 'Who can access it?', 'Live slideshow', 'Price & package'],
    demoTitle: 'See how your guests will upload.', demoText: 'Try the same upload card your guests use. Choose a photo and see it in the demo on this device. No guest account, no app to install.',
    offerTitle: 'Your wedding gallery. Ready for your guests.', offerText: 'Pay once, receive your private setup link by email, add your event details and download your QR code. Put it on the tables and let guests start sharing.',
    limitations: 'Includes up to 20 videos of 60 seconds each. The live slideshow shows eligible photos, not videos. Gallery access lasts 180 days after the event; uploads close at your chosen event end time. Anyone with the link can open it, so share it only with your guests. Download your memories before deletion.',
    faq: 'Before you choose', related: 'Compare another option', sources: 'Sources and comparison notes',
    disclosure: 'Published by Guest Mosaic, one of the products compared. This is a comparison of public product information, not an independent review or a hands-on test of competitors.',
    checked: 'Last checked', package: 'Package compared', priceNote: 'Prices and features can change. Check the provider before purchasing. No currency conversions are used. Where a price could not be verified, we link to the current pricing page.',
    screenshot: 'Guest Mosaic demo gallery: a wedding guest photo with the comments panel',
    summaries: {"whatsapp": "Keep the group chat. Compare it with a QR gallery that brings guest photos together.", "google-drive": "A shared folder or a guest gallery? Compare sign-in, permissions and downloads.", "google-photos": "Compare a shared Google album with guest uploads that need no Google account.", "guestpix": "Two app-free QR galleries. Compare Classic on storage, videos and the slideshow.", "kululu": "Compare Plus on upload limits, photo and video projection, storage and price.", "weduploader": "Photos in your Google Drive or a hosted event gallery? Compare both workflows."},
    facts: {
      qrBrowser: 'QR code or link opens a browser', noAccount: 'No guest account or app', gmMedia: 'Photos, voice messages, 20 videos up to 60 seconds',
      gmDownload: 'Individual originals; ZIP of gallery photo versions', gmRetention: '180 days after event; uploads until chosen end time', gmPrivacy: 'Unlisted; anyone with the link can access', gmSlideshow: 'Eligible photos live on a TV or projector', gmPrice: '€35 once per event, VAT included',
      chat: 'Send media in a chat or group', whatsappAccount: 'WhatsApp account required', chatMedia: 'Photos, videos, voice messages; HD and document options', chatDownload: 'Save media from the conversation', chatRetention: 'Depends on saved copies, deletion and chat settings', encrypted: 'Personal messages are end-to-end encrypted', noEventWall: 'No dedicated live event photo wall in this workflow', freeMessaging: 'Free messaging; data charges may apply',
      folder: 'Upload into a shared folder', googleAccount: 'Google sign-in and permission to add files', files: 'Photos, videos and other files', fileDownload: 'Download files from Drive', googleRetention: 'Google account storage and retention policies apply', permissions: 'Access controlled by folder permissions', googlePrice: '15 GB free shared across Google services; extra storage paid',
      album: 'Contribute to a shared photo album', googlePhotosAccount: 'Google account to contribute to an album', photosVideos: 'Photos and videos', photosDownload: 'Save to your library or download photos', albumSharing: 'Invited accounts or link sharing; collaboration settings',
      guestpixMedia: 'Photos and videos under fair-use terms', guestpixDownload: 'Full-resolution ZIP', guestpixRetention: 'Classic: 3-month uploads, 12-month hosting', sharedLink: 'Access through the shared event link', photoVideoWall: 'Live photo and video wall', livePrice: 'Amount not verified; see current provider price',
      kululuMedia: 'Plus: up to 500 photo and video uploads', bulkDownload: 'Download photos and videos together', kululuRetention: 'Plus: 1-month uploads, 3-month storage', kululuPrice: 'Plus: USD 39 promotional price; USD 79 listed regular price',
      photoWall: 'Live photo wall', driveOriginals: 'Original photos and videos in your Google Drive', driveDownload: 'Files available in the organiser’s Google Drive', wedRetention: 'No album expiry advertised; depends on Google storage', wedPrivacy: 'Organiser connects Google Drive; guest gallery configurable',
    },
  },
  de: {
    hubTitle: 'Findet den passenden Platz für eure Hochzeitsfotos.',
    hubIntro: 'Hochzeitsfotos der Gäste sammeln: Vergleicht WhatsApp, Google Drive, Google Fotos und spezielle Hochzeitsgalerien. Hier seht ihr Unterschiede bei QR-Code, Upload, Preis und Speicherung.',
    eyebrow: 'Hochzeitsfotos teilen im Vergleich', seoTopic: 'Hochzeitsfotos sammeln',
    buy: 'Unsere Galerie erstellen · 35 €', demo: 'Gäste-Demo ausprobieren', compare: 'Zum Vergleich', decision: 'Was passt zu eurer Hochzeit?', choose: 'Wählt', table: 'Was am Hochzeitstag zählt', feature: 'Für eure Hochzeit',
    features: ['Fotos hochladen', 'Gastkonto', 'Fotos & Videos', 'Downloads', 'Speicher- & Upload-Zeitraum', 'Wer hat Zugriff?', 'Live-Diashow', 'Preis & Paket'],
    demoTitle: 'So laden eure Gäste Fotos hoch.', demoText: 'Probiert den Upload aus, den auch eure Gäste nutzen. Wählt ein Foto aus und schaut es euch in der Demo auf diesem Gerät an. Ohne Gastkonto und ohne zusätzliche App.',
    offerTitle: 'Eure Hochzeitsgalerie. Bereit für eure Gäste.', offerText: 'Einmal bezahlen, privaten Einrichtungslink per E-Mail erhalten, Veranstaltungsdaten ergänzen und QR-Code herunterladen. Auf die Tische stellen und die Gäste können loslegen.',
    limitations: 'Enthalten sind bis zu 20 Videos mit jeweils 60 Sekunden. Die Live-Diashow zeigt geeignete Fotos, keine Videos. Die Galerie bleibt 180 Tage nach dem Event verfügbar; Uploads enden zum festgelegten Veranstaltungsende. Jeder mit dem Link kann zugreifen. Teilt ihn nur mit euren Gästen und ladet eure Erinnerungen vor der Löschung herunter.',
    faq: 'Vor eurer Entscheidung', related: 'Weitere Alternativen vergleichen', sources: 'Quellen und Hinweise zum Vergleich', disclosure: 'Veröffentlicht von Guest Mosaic, einem der verglichenen Anbieter. Grundlage sind öffentliche Produktinformationen, keine unabhängige Bewertung und kein Praxistest der Konkurrenz.',
    checked: 'Zuletzt geprüft', package: 'Verglichenes Paket', priceNote: 'Preise und Funktionen können sich ändern. Prüft die Angaben vor dem Kauf beim Anbieter. Wir rechnen keine Währungen um. Bei nicht bestätigten Preisen verlinken wir die aktuelle Preisseite.', screenshot: 'Guest Mosaic Demogalerie: ein Hochzeitsfoto mit geöffneten Kommentaren',
    summaries: {"whatsapp": "Gruppenchat behalten, Fotos gemeinsam sammeln: WhatsApp und QR-Galerie im Vergleich.", "google-drive": "Geteilter Ordner oder Gästegalerie? Vergleicht Anmeldung, Berechtigungen und Downloads.", "google-photos": "Geteiltes Google-Album oder Upload ohne Google-Konto? So unterscheiden sich die Abläufe.", "guestpix": "Zwei QR-Galerien ohne App. Vergleicht Classic bei Speicherung, Videos und Diashow.", "kululu": "Vergleicht Plus bei Upload-Limits, Foto- und Videoprojektion, Speicherung und Preis.", "weduploader": "Fotos im eigenen Google Drive oder in einer gehosteten Eventgalerie? Vergleicht beide Abläufe."},
    facts: {
      qrBrowser: 'QR-Code oder Link öffnet den Browser', noAccount: 'Kein Gastkonto und keine App', gmMedia: 'Fotos, Sprachnachrichten, 20 Videos bis 60 Sekunden', gmDownload: 'Einzelne Originale; ZIP mit Galerieversionen der Fotos', gmRetention: '180 Tage nach dem Event; Upload bis zum gewählten Ende', gmPrivacy: 'Nicht öffentlich gelistet; Zugriff mit dem Link', gmSlideshow: 'Geeignete Fotos live auf TV oder Beamer', gmPrice: '35 € einmalig pro Event, inklusive MwSt.',
      chat: 'Medien im Chat oder in einer Gruppe senden', whatsappAccount: 'WhatsApp-Konto erforderlich', chatMedia: 'Fotos, Videos, Sprachnachrichten; HD und Dokumentversand', chatDownload: 'Medien aus dem Chat speichern', chatRetention: 'Abhängig von Kopien, Löschung und Chat-Einstellungen', encrypted: 'Persönliche Nachrichten sind Ende-zu-Ende-verschlüsselt', noEventWall: 'Keine spezielle Live-Fotowand in diesem Ablauf', freeMessaging: 'Kostenlose Nachrichten; mögliche Datenkosten', folder: 'Dateien in einen freigegebenen Ordner hochladen', googleAccount: 'Google-Anmeldung und Berechtigung zum Hochladen', files: 'Fotos, Videos und andere Dateien', fileDownload: 'Dateien aus Drive herunterladen', googleRetention: 'Speicher- und Aufbewahrungsregeln des Google-Kontos', permissions: 'Zugriff über Ordnerberechtigungen', googlePrice: '15 GB kostenlos für Google-Dienste gemeinsam; mehr Speicher kostenpflichtig', album: 'Zu einem geteilten Fotoalbum beitragen', googlePhotosAccount: 'Google-Konto zum Hinzufügen von Fotos', photosVideos: 'Fotos und Videos', photosDownload: 'In Mediathek speichern oder Fotos herunterladen', albumSharing: 'Eingeladene Konten oder Link; Freigabeeinstellungen', guestpixMedia: 'Fotos und Videos nach Fair-Use-Regeln', guestpixDownload: 'ZIP in voller Auflösung', guestpixRetention: 'Classic: 3 Monate Upload, 12 Monate Hosting', sharedLink: 'Zugriff über den geteilten Event-Link', photoVideoWall: 'Live-Fotowand mit Fotos und Videos', livePrice: 'Betrag nicht bestätigt; aktuellen Anbieterpreis prüfen', kululuMedia: 'Plus: bis zu 500 Foto- und Video-Uploads', bulkDownload: 'Fotos und Videos gemeinsam herunterladen', kululuRetention: 'Plus: 1 Monat Upload, 3 Monate Speicherung', kululuPrice: 'Plus: Aktionspreis 39 USD; regulär angegeben 79 USD', photoWall: 'Live-Fotowand', driveOriginals: 'Originalfotos und -videos in eurem Google Drive', driveDownload: 'Dateien im Google Drive des Veranstalters', wedRetention: 'Laut Anbieter kein Albumablauf; abhängig vom Google-Speicher', wedPrivacy: 'Veranstalter verbindet Google Drive; Gästegalerie einstellbar',
    },
  },
  nl: {
    hubTitle: 'Kies een plek voor alle trouwfoto’s van jullie gasten.', hubIntro: 'Vergelijk WhatsApp, Google Drive, Google Foto’s en speciale trouwgalerijen. Ontdek hoe je foto’s van gasten verzamelt en wat de verschillen zijn in QR-codes, uploads, kosten en opslag.',
    eyebrow: 'Trouwfoto’s delen en verzamelen', seoTopic: 'Trouwfoto’s delen', buy: 'Maak onze galerij · €35', demo: 'Probeer de gastdemo', compare: 'Bekijk de vergelijking', decision: 'Wat past bij jullie bruiloft?', choose: 'Kies', table: 'De verschillen voor jullie trouwdag', feature: 'Voor jullie bruiloft',
    features: ['Foto’s uploaden', 'Gastaccount', 'Foto’s & video’s', 'Downloads', 'Opslag & uploadperiode', 'Wie heeft toegang?', 'Live diavoorstelling', 'Prijs & pakket'],
    demoTitle: 'Zo uploaden jullie gasten hun foto’s.', demoText: 'Probeer dezelfde upload als jullie gasten. Kies een foto en bekijk die in de demo op dit apparaat. Geen gastaccount en geen app nodig.', offerTitle: 'Jullie trouwgalerij. Klaar voor de gasten.', offerText: 'Betaal eenmalig en ontvang een privélink per e-mail. Vul jullie gegevens in en download de QR-code. Zet die op de tafels, zodat gasten hun foto’s kunnen delen.',
    limitations: 'Inclusief maximaal 20 video’s van elk 60 seconden. De live diavoorstelling toont geschikte foto’s, geen video’s. De galerij blijft 180 dagen na het evenement beschikbaar; uploaden stopt op de ingestelde eindtijd. Iedereen met de link heeft toegang. Deel die alleen met jullie gasten en download alles vóór verwijdering.',
    faq: 'Voordat jullie kiezen', related: 'Vergelijk een andere optie', sources: 'Bronnen en toelichting', disclosure: 'Gepubliceerd door Guest Mosaic, een van de vergeleken aanbieders. Gebaseerd op openbare productinformatie, niet op een onafhankelijke review of praktijktest van concurrenten.', checked: 'Laatst gecontroleerd', package: 'Vergeleken pakket', priceNote: 'Prijzen en functies kunnen veranderen. Controleer ze bij de aanbieder voordat je koopt. We rekenen valuta niet om. Bij een onbevestigd bedrag verwijzen we naar de actuele prijspagina.', screenshot: 'Guest Mosaic demogalerij: een trouwfoto met het reactiepaneel',
    summaries: {"whatsapp": "Behoud de groepschat. Vergelijk WhatsApp met een QR-galerij voor alle gastfoto’s.", "google-drive": "Een gedeelde map of een gastgalerij? Vergelijk inloggen, rechten en downloads.", "google-photos": "Vergelijk een gedeeld Google-album met uploads waarvoor gasten geen Google-account nodig hebben.", "guestpix": "Twee QR-galerijen zonder app. Vergelijk Classic op opslag, video’s en de diavoorstelling.", "kululu": "Vergelijk Plus op uploadlimieten, foto- en videoprojectie, opslag en prijs.", "weduploader": "Foto’s in jullie Google Drive of een gehoste evenementgalerij? Vergelijk beide werkwijzen."},
    facts: {
      qrBrowser: 'QR-code of link opent de browser', noAccount: 'Geen gastaccount of app', gmMedia: 'Foto’s, spraakberichten, 20 video’s tot 60 seconden', gmDownload: 'Losse originelen; ZIP met galerijversies van foto’s', gmRetention: '180 dagen na het evenement; upload tot gekozen eindtijd', gmPrivacy: 'Niet openbaar vermeld; toegang met de link', gmSlideshow: 'Geschikte foto’s live op tv of projector', gmPrice: '€35 eenmalig per evenement, inclusief btw', chat: 'Media in een chat of groep sturen', whatsappAccount: 'WhatsApp-account nodig', chatMedia: 'Foto’s, video’s, spraakberichten; HD en documenten', chatDownload: 'Media uit het gesprek opslaan', chatRetention: 'Afhankelijk van kopieën, verwijdering en chatinstellingen', encrypted: 'Persoonlijke berichten zijn end-to-end versleuteld', noEventWall: 'Geen speciale live fotowand in deze werkwijze', freeMessaging: 'Gratis berichten; datakosten mogelijk', folder: 'Uploaden naar een gedeelde map', googleAccount: 'Google-account en toestemming om bestanden toe te voegen', files: 'Foto’s, video’s en andere bestanden', fileDownload: 'Bestanden downloaden uit Drive', googleRetention: 'Opslag- en bewaarbeleid van het Google-account', permissions: 'Toegang via mapmachtigingen', googlePrice: '15 GB gratis gedeeld met Google-diensten; extra opslag betaald', album: 'Bijdragen aan een gedeeld fotoalbum', googlePhotosAccount: 'Google-account om foto’s toe te voegen', photosVideos: 'Foto’s en video’s', photosDownload: 'Opslaan in je bibliotheek of foto’s downloaden', albumSharing: 'Uitgenodigde accounts of link; instellingen voor samenwerken', guestpixMedia: 'Foto’s en video’s onder fair-usevoorwaarden', guestpixDownload: 'ZIP in volledige resolutie', guestpixRetention: 'Classic: 3 maanden upload, 12 maanden hosting', sharedLink: 'Toegang via de gedeelde evenementlink', photoVideoWall: 'Live fotowand met foto’s en video’s', livePrice: 'Bedrag niet bevestigd; bekijk de actuele prijs', kululuMedia: 'Plus: maximaal 500 foto- en video-uploads', bulkDownload: 'Foto’s en video’s samen downloaden', kululuRetention: 'Plus: 1 maand upload, 3 maanden opslag', kululuPrice: 'Plus: actieprijs USD 39; vermelde normale prijs USD 79', photoWall: 'Live fotowand', driveOriginals: 'Originele foto’s en video’s in jullie Google Drive', driveDownload: 'Bestanden in de Google Drive van de organisator', wedRetention: 'Geen vervaldatum voor albums geadverteerd; Google-opslag bepaalt ruimte', wedPrivacy: 'Organisator koppelt Google Drive; gastgalerij instelbaar',
    },
  },
  es: {
    hubTitle: 'Un lugar para las fotos de todos vuestros invitados.', hubIntro: 'Compara WhatsApp, Google Drive, Google Fotos y galerías de boda. Descubre cómo recopilar fotos de invitados, compartir un código QR y elegir según el precio, las descargas y el almacenamiento.',
    eyebrow: 'Compartir fotos de boda: comparativa', seoTopic: 'Compartir fotos de boda', buy: 'Crear nuestra galería · 35 €', demo: 'Probar la demo para invitados', compare: 'Ver comparación', decision: '¿Qué encaja con vuestra boda?', choose: 'Elegid', table: 'Las diferencias que cuentan el día de la boda', feature: 'Para vuestra boda',
    features: ['Subida de fotos', 'Cuenta del invitado', 'Fotos y vídeos', 'Descargas', 'Almacenamiento y plazo de subida', '¿Quién puede acceder?', 'Proyección en directo', 'Precio y paquete'],
    demoTitle: 'Así subirán las fotos vuestros invitados.', demoText: 'Probad el mismo formulario que usarán vuestros invitados. Elegid una foto y vedla en la demo de este dispositivo. Sin cuenta de invitado ni aplicación.', offerTitle: 'Vuestra galería de boda, lista para los invitados.', offerText: 'Pagad una vez y recibid por correo un enlace privado de configuración. Añadid los datos del evento y descargad el QR. Colocadlo en las mesas para empezar a recibir fotos.',
    limitations: 'Incluye hasta 20 vídeos de 60 segundos cada uno. La proyección en directo muestra fotos aptas, no vídeos. La galería dura 180 días tras el evento; las subidas terminan a la hora de cierre elegida. Cualquiera con el enlace puede acceder. Compartidlo solo con los invitados y descargad los recuerdos antes de su eliminación.',
    faq: 'Antes de elegir', related: 'Comparar otra opción', sources: 'Fuentes y notas de la comparación', disclosure: 'Publicado por Guest Mosaic, uno de los productos comparados. Basado en información pública de los proveedores; no es una reseña independiente ni una prueba práctica de la competencia.', checked: 'Última comprobación', package: 'Paquete comparado', priceNote: 'Los precios y las funciones pueden cambiar. Comprobadlos con el proveedor antes de comprar. No convertimos divisas. Si no se pudo verificar un importe, enlazamos su página de precios actual.', screenshot: 'Galería de demostración Guest Mosaic: foto de boda y panel de comentarios',
    summaries: {"whatsapp": "Conservad el chat del grupo. Comparad WhatsApp con una galería QR para reunir las fotos.", "google-drive": "¿Carpeta compartida o galería para invitados? Comparad acceso, permisos y descargas.", "google-photos": "Comparad un álbum de Google compartido con subidas sin cuenta de Google.", "guestpix": "Dos galerías QR sin app. Comparad Classic en almacenamiento, vídeos y proyección.", "kululu": "Comparad Plus en límites de subida, proyección de fotos y vídeos, almacenamiento y precio.", "weduploader": "¿Fotos en vuestro Google Drive o en una galería alojada? Comparad cómo funciona cada opción."},
    facts: {
      qrBrowser: 'El QR o enlace abre el navegador', noAccount: 'Sin cuenta de invitado ni app', gmMedia: 'Fotos, mensajes de voz, 20 vídeos de hasta 60 segundos', gmDownload: 'Originales individuales; ZIP con versiones de galería de las fotos', gmRetention: '180 días tras el evento; subidas hasta el cierre elegido', gmPrivacy: 'No indexada; acceso para cualquiera con el enlace', gmSlideshow: 'Fotos aptas en directo en TV o proyector', gmPrice: '35 € por evento, pago único con IVA', chat: 'Enviar archivos en un chat o grupo', whatsappAccount: 'Requiere cuenta de WhatsApp', chatMedia: 'Fotos, vídeos, voz; opciones HD y documentos', chatDownload: 'Guardar archivos de la conversación', chatRetention: 'Depende de copias, borrado y ajustes del chat', encrypted: 'Mensajes personales cifrados de extremo a extremo', noEventWall: 'Sin muro de fotos en directo específico en este flujo', freeMessaging: 'Mensajería gratuita; pueden aplicarse costes de datos', folder: 'Subir a una carpeta compartida', googleAccount: 'Cuenta de Google y permiso para añadir archivos', files: 'Fotos, vídeos y otros archivos', fileDownload: 'Descargar archivos desde Drive', googleRetention: 'Se aplican las políticas de almacenamiento de Google', permissions: 'Acceso según los permisos de la carpeta', googlePrice: '15 GB gratis compartidos entre servicios de Google; espacio adicional de pago', album: 'Añadir fotos a un álbum compartido', googlePhotosAccount: 'Cuenta de Google para contribuir al álbum', photosVideos: 'Fotos y vídeos', photosDownload: 'Guardar en la biblioteca o descargar fotos', albumSharing: 'Cuentas invitadas o enlace; ajustes de colaboración', guestpixMedia: 'Fotos y vídeos sujetos a uso razonable', guestpixDownload: 'ZIP en resolución completa', guestpixRetention: 'Classic: 3 meses de subidas, 12 de alojamiento', sharedLink: 'Acceso mediante el enlace compartido del evento', photoVideoWall: 'Muro en directo con fotos y vídeos', livePrice: 'Importe no verificado; consultar precio actual', kululuMedia: 'Plus: hasta 500 subidas de fotos y vídeos', bulkDownload: 'Descarga conjunta de fotos y vídeos', kululuRetention: 'Plus: 1 mes de subidas, 3 de almacenamiento', kululuPrice: 'Plus: oferta de 39 USD; precio habitual indicado de 79 USD', photoWall: 'Muro de fotos en directo', driveOriginals: 'Fotos y vídeos originales en vuestro Google Drive', driveDownload: 'Archivos en el Google Drive del organizador', wedRetention: 'Sin caducidad de álbum anunciada; depende del almacenamiento de Google', wedPrivacy: 'El organizador conecta Google Drive; galería configurable',
    },
  },
  it: {
    hubTitle: 'Scegliete dove raccogliere le foto del vostro matrimonio.', hubIntro: 'Confrontate WhatsApp, Google Drive, Google Foto e le gallerie per matrimoni. Scoprite le differenze tra caricamento degli invitati, codice QR, prezzi, download e archiviazione.',
    eyebrow: 'Foto del matrimonio: soluzioni a confronto', seoTopic: 'Condividere foto del matrimonio', buy: 'Crea la nostra galleria · 35 €', demo: 'Prova la demo per gli invitati', compare: 'Vedi il confronto', decision: 'Cosa fa per il vostro matrimonio?', choose: 'Scegliete', table: 'Le differenze che contano il giorno delle nozze', feature: 'Per il vostro matrimonio',
    features: ['Caricamento degli invitati', 'Account ospite', 'Foto e video', 'Download', 'Archiviazione e periodo di caricamento', 'Chi può accedere?', 'Slideshow dal vivo', 'Prezzo e pacchetto'],
    demoTitle: 'Ecco come caricheranno le foto i vostri invitati.', demoText: 'Provate lo stesso modulo che useranno gli invitati. Scegliete una foto e guardatela nella demo su questo dispositivo. Nessun account ospite, nessuna app da installare.', offerTitle: 'La vostra galleria di nozze. Pronta per gli invitati.', offerText: 'Pagate una volta e ricevete via email il link privato di configurazione. Aggiungete i dettagli dell’evento e scaricate il QR. Posizionatelo sui tavoli e gli invitati potranno condividere le foto.',
    limitations: 'Include fino a 20 video di 60 secondi ciascuno. Lo slideshow mostra le foto idonee, non i video. La galleria resta disponibile per 180 giorni dopo l’evento; i caricamenti terminano all’orario scelto. Chiunque abbia il link può accedere. Condividetelo solo con gli invitati e scaricate i ricordi prima della cancellazione.',
    faq: 'Prima di scegliere', related: 'Confronta un’altra opzione', sources: 'Fonti e note sul confronto', disclosure: 'Pubblicato da Guest Mosaic, uno dei prodotti confrontati. Basato sulle informazioni pubbliche dei fornitori, non su una recensione indipendente o una prova pratica dei concorrenti.', checked: 'Ultima verifica', package: 'Pacchetto confrontato', priceNote: 'Prezzi e funzionalità possono cambiare. Verificateli sul sito del fornitore prima dell’acquisto. Non convertiamo le valute. Se un importo non è verificabile, rimandiamo al listino attuale.', screenshot: 'Galleria demo Guest Mosaic: una foto di matrimonio con il pannello dei commenti',
    summaries: {"whatsapp": "Tenete la chat di gruppo. Confrontate WhatsApp con una galleria QR per riunire le foto.", "google-drive": "Cartella condivisa o galleria per gli invitati? Confrontate accesso, permessi e download.", "google-photos": "Confrontate un album Google condiviso con caricamenti senza account Google.", "guestpix": "Due gallerie QR senza app. Confrontate Classic su archiviazione, video e slideshow.", "kululu": "Confrontate Plus su limiti di caricamento, proiezione di foto e video, archiviazione e prezzo.", "weduploader": "Foto nel vostro Google Drive o in una galleria ospitata? Confrontate i due percorsi."},
    facts: {
      qrBrowser: 'Il QR o il link apre il browser', noAccount: 'Nessun account ospite o app', gmMedia: 'Foto, messaggi vocali, 20 video fino a 60 secondi', gmDownload: 'Originali singoli; ZIP delle versioni foto della galleria', gmRetention: '180 giorni dopo l’evento; caricamenti fino alla fine scelta', gmPrivacy: 'Non indicizzata; accessibile a chi ha il link', gmSlideshow: 'Foto idonee dal vivo su TV o proiettore', gmPrice: '35 € una tantum per evento, IVA inclusa', chat: 'Invio di file in una chat o gruppo', whatsappAccount: 'Account WhatsApp richiesto', chatMedia: 'Foto, video, vocali; opzioni HD e documenti', chatDownload: 'Salvare i file dalla conversazione', chatRetention: 'Dipende da copie, eliminazione e impostazioni della chat', encrypted: 'Messaggi personali con crittografia end-to-end', noEventWall: 'Nessuna parete foto live dedicata in questo flusso', freeMessaging: 'Messaggi gratuiti; possibili costi dati', folder: 'Caricare in una cartella condivisa', googleAccount: 'Accesso Google e permesso di aggiungere file', files: 'Foto, video e altri file', fileDownload: 'Scaricare i file da Drive', googleRetention: 'Si applicano le politiche di archiviazione dell’account Google', permissions: 'Accesso tramite permessi della cartella', googlePrice: '15 GB gratuiti condivisi tra servizi Google; spazio extra a pagamento', album: 'Contribuire a un album fotografico condiviso', googlePhotosAccount: 'Account Google per contribuire all’album', photosVideos: 'Foto e video', photosDownload: 'Salvare nella raccolta o scaricare foto', albumSharing: 'Account invitati o link; impostazioni di collaborazione', guestpixMedia: 'Foto e video soggetti a uso corretto', guestpixDownload: 'ZIP a piena risoluzione', guestpixRetention: 'Classic: 3 mesi di caricamenti, 12 di hosting', sharedLink: 'Accesso tramite link condiviso dell’evento', photoVideoWall: 'Parete live con foto e video', livePrice: 'Importo non verificato; consultare il prezzo attuale', kululuMedia: 'Plus: fino a 500 caricamenti di foto e video', bulkDownload: 'Download congiunto di foto e video', kululuRetention: 'Plus: 1 mese di caricamenti, 3 di archiviazione', kululuPrice: 'Plus: promozione a 39 USD; prezzo ordinario indicato 79 USD', photoWall: 'Parete fotografica dal vivo', driveOriginals: 'Foto e video originali nel vostro Google Drive', driveDownload: 'File nel Google Drive dell’organizzatore', wedRetention: 'Nessuna scadenza dell’album dichiarata; dipende dallo spazio Google', wedPrivacy: 'L’organizzatore collega Google Drive; galleria configurabile',
    },
  },
  fr: {
    hubTitle: 'Trouvez où réunir les photos de votre mariage.', hubIntro: 'Comparez WhatsApp, Google Drive, Google Photos et les galeries de mariage. Découvrez les différences de partage par QR code, de dépôt des photos, de prix et de conservation.',
    eyebrow: 'Partage de photos de mariage : le comparatif', seoTopic: 'Partage de photos de mariage', buy: 'Créer notre galerie · 35 €', demo: 'Essayer la démo invités', compare: 'Voir le comparatif', decision: 'Quelle solution pour votre mariage ?', choose: 'Choisissez', table: 'Ce qui compte le jour du mariage', feature: 'Pour votre mariage',
    features: ['Dépôt des photos', 'Compte invité', 'Photos et vidéos', 'Téléchargements', 'Conservation et période de dépôt', 'Qui peut y accéder ?', 'Diaporama en direct', 'Prix et formule'],
    demoTitle: 'Découvrez comment vos invités déposeront leurs photos.', demoText: 'Essayez le même formulaire que vos invités. Choisissez une photo et retrouvez-la dans la démo sur cet appareil. Aucun compte invité ni application à installer.', offerTitle: 'Votre galerie de mariage. Prête pour vos invités.', offerText: 'Payez une fois, recevez votre lien privé de configuration par e-mail, ajoutez les détails du mariage et téléchargez votre QR code. Posez-le sur les tables pour commencer à recevoir les photos.',
    limitations: 'Comprend jusqu’à 20 vidéos de 60 secondes chacune. Le diaporama affiche les photos admissibles, pas les vidéos. La galerie reste accessible 180 jours après l’événement ; les dépôts ferment à l’heure de fin choisie. Toute personne disposant du lien peut y accéder. Partagez-le uniquement avec vos invités et téléchargez vos souvenirs avant leur suppression.',
    faq: 'Avant de choisir', related: 'Comparer une autre solution', sources: 'Sources et notes du comparatif', disclosure: 'Publié par Guest Mosaic, l’un des produits comparés. Ce comparatif repose sur les informations publiques des fournisseurs, pas sur un avis indépendant ni un essai pratique des concurrents.', checked: 'Dernière vérification', package: 'Formule comparée', priceNote: 'Les prix et fonctionnalités peuvent évoluer. Vérifiez-les auprès du fournisseur avant l’achat. Nous ne convertissons pas les devises. Si un montant n’a pas pu être vérifié, nous renvoyons vers la page tarifaire actuelle.', screenshot: 'Galerie démo Guest Mosaic : une photo de mariage avec les commentaires',
    summaries: {"whatsapp": "Gardez la conversation de groupe. Comparez WhatsApp à une galerie QR pour réunir les photos.", "google-drive": "Dossier partagé ou galerie invités ? Comparez la connexion, les autorisations et les téléchargements.", "google-photos": "Comparez un album Google partagé au dépôt de photos sans compte Google.", "guestpix": "Deux galeries QR sans application. Comparez Classic sur la conservation, les vidéos et le diaporama.", "kululu": "Comparez Plus sur les limites de dépôt, la projection photo et vidéo, la conservation et le prix.", "weduploader": "Les photos dans votre Google Drive ou une galerie hébergée ? Comparez les deux parcours."},
    facts: {
      qrBrowser: 'Le QR code ou le lien ouvre le navigateur', noAccount: 'Aucun compte invité ni application', gmMedia: 'Photos, messages vocaux, 20 vidéos de 60 secondes maximum', gmDownload: 'Originaux individuels ; ZIP des versions galerie des photos', gmRetention: '180 jours après l’événement ; dépôts jusqu’à la fin choisie', gmPrivacy: 'Non répertoriée ; accessible avec le lien', gmSlideshow: 'Photos admissibles en direct sur TV ou projecteur', gmPrice: '35 € par événement, paiement unique TTC', chat: 'Envoyer les médias dans un groupe ou une conversation', whatsappAccount: 'Compte WhatsApp nécessaire', chatMedia: 'Photos, vidéos, messages vocaux ; options HD et documents', chatDownload: 'Enregistrer les médias de la conversation', chatRetention: 'Selon les copies, suppressions et réglages du chat', encrypted: 'Messages personnels chiffrés de bout en bout', noEventWall: 'Pas de mur photo événementiel en direct dans ce parcours', freeMessaging: 'Messagerie gratuite ; frais de données possibles', folder: 'Importer dans un dossier partagé', googleAccount: 'Connexion Google et autorisation d’ajouter des fichiers', files: 'Photos, vidéos et autres fichiers', fileDownload: 'Télécharger les fichiers depuis Drive', googleRetention: 'Règles de stockage et de conservation du compte Google', permissions: 'Accès selon les autorisations du dossier', googlePrice: '15 Go gratuits partagés entre services Google ; stockage supplémentaire payant', album: 'Contribuer à un album photo partagé', googlePhotosAccount: 'Compte Google pour contribuer à l’album', photosVideos: 'Photos et vidéos', photosDownload: 'Enregistrer dans la photothèque ou télécharger les photos', albumSharing: 'Comptes invités ou lien ; réglages de collaboration', guestpixMedia: 'Photos et vidéos sous conditions d’utilisation raisonnable', guestpixDownload: 'ZIP en pleine résolution', guestpixRetention: 'Classic : 3 mois de dépôt, 12 mois d’hébergement', sharedLink: 'Accès par le lien partagé de l’événement', photoVideoWall: 'Mur de photos et vidéos en direct', livePrice: 'Montant non vérifié ; consulter le tarif actuel', kululuMedia: 'Plus : jusqu’à 500 dépôts de photos et vidéos', bulkDownload: 'Téléchargement groupé des photos et vidéos', kululuRetention: 'Plus : 1 mois de dépôt, 3 mois de stockage', kululuPrice: 'Plus : promotion à 39 USD ; tarif habituel affiché de 79 USD', photoWall: 'Mur photo en direct', driveOriginals: 'Photos et vidéos originales dans votre Google Drive', driveDownload: 'Fichiers dans le Google Drive de l’organisateur', wedRetention: 'Aucune expiration d’album annoncée ; dépend du stockage Google', wedPrivacy: 'L’organisateur connecte Google Drive ; galerie invités configurable',
    },
  },
});
