import type { SolutionPageContent } from "./solution-pages";

type RomanceLocale = "es" | "it" | "fr";

export const romanceSolutionPages: Record<RomanceLocale, Record<SolutionPageContent["id"], SolutionPageContent>> = {
  es: {
    "wedding-qr": {
      id: "wedding-qr",
      seoTitle: "Código QR para fotos de boda | Guest Mosaic",
      metaDescription: "Reúne las fotos y los vídeos cortos de tus invitados en una galería compartida. Escanean un código QR y suben desde el navegador. 35 € por evento.",
      navTitle: "Código QR para fotos de boda",
      eyebrow: "Fotos de boda compartidas con un código QR",
      title: "Todas las fotos de vuestros invitados con un solo código QR.",
      description: "Colocad el código en la bienvenida, las mesas o las invitaciones. Los invitados lo escanean y suben fotos, vídeos cortos y mensajes desde el móvil, sin aplicación ni cuenta.",
      primaryCta: "Crear galería de boda — 35 €",
      secondaryCta: "Probar la subida como invitado",
      trust: ["35 € por evento · IVA incluido · sin suscripción", "Invitados ilimitados", "Galería disponible 180 días tras el evento"],
      benefitsPill: "Cada perspectiva en un solo lugar",
      benefitsHeading: "Dejad de perseguir fotos después de la boda.",
      benefitsIntro: "Sustituid las fotos comprimidas de los chats, los enlaces dispersos y los recordatorios por una única forma de participar.",
      benefits: [
        { title: "Fácil para los invitados", description: "Escanear, elegir y subir. Sin descargas, registros ni contraseñas." },
        { title: "Lista para vuestra papelería", description: "Descargad el QR en SVG o PNG para carteles, tarjetas, menús y pantallas." },
        { title: "Momentos espontáneos", description: "Reunid la pista de baile, las mesas y todo lo que ven vuestros invitados." },
        { title: "Todo junto al terminar", description: "Revisad la galería, descargad originales y solicitad el ZIP por correo." },
      ],
      clarityPill: "Claro desde el principio",
      clarityHeading: "Una galería compartida, no un sustituto del fotógrafo.",
      clarityText: "El fotógrafo captura las imágenes esenciales. Guest Mosaic reúne los momentos espontáneos de cada mesa. La galería no se indexa; quien tenga el enlace o QR puede abrirla.",
      clarityItems: ["Compartid el enlace solo con vuestros invitados", "Podéis revisar las fotos antes de mostrarlas", "Descargad los recuerdos antes de que termine la conservación"],
      faqPill: "Antes de empezar",
      faqHeading: "Preguntas sobre el código QR para bodas",
      faq: [
        ["¿Los invitados necesitan una aplicación?", "No. El QR abre la galería en el navegador y no exige crear una cuenta."],
        ["¿Dónde mostramos el código QR?", "En la bienvenida, mesas, menús, barra, photocall y cerca de la pista de baile."],
        ["¿Pueden subir vídeos?", "Sí. El evento incluye hasta 20 vídeos de 60 segundos. Aparecen en la galería, no en el Live Slideshow."],
        ["¿La galería es privada?", "No se indexa públicamente, pero no tiene contraseña por defecto. Quien tenga el enlace o QR puede abrirla."],
        ["¿Cuánto tiempo está disponible?", "Los archivos se conservan normalmente durante 180 días después del evento."],
      ],
      relatedHeading: "Otras formas de reunir fotos de eventos",
      relatedLink: "Ver solución",
    },
    "no-app-sharing": {
      id: "no-app-sharing",
      seoTitle: "Compartir fotos de eventos sin aplicación | Guest Mosaic",
      metaDescription: "Los invitados escanean un QR y suben fotos desde el navegador. Sin aplicación, registro ni cuenta. Una galería compartida por 35 €.",
      navTitle: "Compartir fotos sin aplicación",
      eyebrow: "Fotos de eventos desde el navegador",
      title: "Compartid fotos del evento sin pedir que instalen una aplicación.",
      description: "Un código QR abre la subida en el navegador del móvil. Los invitados eligen sus fotos, las añaden al evento y vuelven a la celebración.",
      primaryCta: "Crear galería — 35 €",
      secondaryCta: "Probar como invitado",
      trust: ["35 € por evento · IVA incluido", "Sin cuenta para invitados", "Invitados ilimitados"],
      benefitsPill: "Menos fricción",
      benefitsHeading: "El camino corto del carrete a la galería.",
      benefitsIntro: "Los invitados participan desde el dispositivo que ya tienen en la mano.",
      benefits: [
        { title: "Sin tienda de aplicaciones", description: "La página se abre desde la cámara o el enlace del evento." },
        { title: "Sin cuentas", description: "Nadie introduce correo, crea contraseña ni se registra." },
        { title: "Varias fotos a la vez", description: "Se pueden seleccionar varios archivos y seguir su progreso." },
        { title: "Reintentos claros", description: "Si falla una transferencia, se puede intentar de nuevo." },
      ],
      clarityPill: "Qué esperar",
      clarityHeading: "Sencillo en el navegador y honesto con la conexión.",
      clarityText: "Guest Mosaic funciona en navegadores móviles modernos. La fiabilidad depende del dispositivo y la conexión; las transferencias fallidas se pueden repetir.",
      clarityItems: ["Abrir con QR o enlace", "Sin correo ni contraseña", "Una galería para todo el evento"],
      faqPill: "Antes del evento",
      faqHeading: "Preguntas sobre compartir fotos sin app",
      faq: [
        ["¿Hace falta una cuenta?", "No. Los invitados abren el evento y suben desde el navegador."],
        ["¿Podemos compartir un enlace?", "Sí. El enlace y el QR abren la misma galería."],
        ["¿Qué ocurre con mala conexión?", "El progreso se muestra por archivo y cada fallo se puede reintentar."],
        ["¿Quién puede abrir la galería?", "No se indexa, pero cualquiera con el enlace o QR puede abrirla."],
      ],
      relatedHeading: "Elegid la forma adecuada de compartir fotos",
      relatedLink: "Ver solución",
    },
    "event-qr-gallery": {
      id: "event-qr-gallery",
      seoTitle: "Código QR para compartir fotos de eventos | Guest Mosaic",
      metaDescription: "Reúne fotos, vídeos cortos y mensajes en una galería QR compartida. Sin aplicación ni cuenta. 35 € por evento, IVA incluido.",
      navTitle: "Código QR para fotos de eventos",
      eyebrow: "Galería QR para eventos",
      title: "Un código QR para todas las fotos del evento.",
      description: "Los invitados escanean, suben y navegan desde el móvil. Todo queda reunido en una galería compartida sin suscripción.",
      primaryCta: "Crear galería QR — 35 €",
      secondaryCta: "Ver evento de demostración",
      trust: ["35 € por evento · IVA incluido", "Invitados ilimitados", "Sin aplicación"],
      benefitsPill: "Un evento, un destino",
      benefitsHeading: "Participar es obvio; reunirlo, automático.",
      benefitsIntro: "Usad el mismo QR en carteles, mesas, acreditaciones y pantallas.",
      benefits: [
        { title: "Acceso rápido", description: "Escanear y subir desde el navegador sin cuenta." },
        { title: "Más que fotos", description: "Reunid fotos, hasta 20 vídeos cortos y mensajes de voz." },
        { title: "Control de visibilidad", description: "Revisad las aportaciones antes de mostrarlas." },
        { title: "Descarga sencilla", description: "Descargad originales o solicitad un ZIP temporal." },
      ],
      clarityPill: "Para cada ocasión",
      clarityHeading: "De bodas a eventos de empresa.",
      clarityText: "El mismo flujo sirve para celebraciones, cumpleaños, team buildings, congresos y ferias.",
      clarityItems: ["Bodas y celebraciones", "Team buildings y eventos corporativos", "Congresos y ferias"],
      faqPill: "Planifica la galería",
      faqHeading: "Preguntas sobre galerías QR",
      faq: [
        ["¿Cuántos invitados pueden participar?", "El evento no tiene límite por invitado."],
        ["¿Podemos mostrar fotos en una pantalla?", "Sí. El Live Slideshow muestra las fotos aptas y aprobadas."],
        ["¿Se puede subir después del evento?", "La subida se cierra en la fecha y hora final configuradas."],
        ["¿Hay suscripción?", "No. El precio base es 35 € con IVA por evento."],
      ],
      relatedHeading: "Explora opciones para compartir fotos",
      relatedLink: "Ver solución",
    },
  },
  it: {
    "wedding-qr": {
      id: "wedding-qr",
      seoTitle: "Codice QR per le foto del matrimonio | Guest Mosaic",
      metaDescription: "Raccogli foto e brevi video degli invitati in una galleria condivisa. Scansionano un QR e caricano dal browser. 35 € per evento.",
      navTitle: "Codice QR per foto di matrimonio",
      eyebrow: "Foto del matrimonio condivise con un QR",
      title: "Tutte le foto dei vostri invitati con un solo codice QR.",
      description: "Mettete il codice sul cartello di benvenuto, sui tavoli o sugli inviti. Gli ospiti caricano foto, brevi video e messaggi dal telefono, senza app né account.",
      primaryCta: "Crea la galleria — 35 €",
      secondaryCta: "Prova il caricamento come ospite",
      trust: ["35 € per evento · IVA inclusa · nessun abbonamento", "Ospiti illimitati", "Galleria disponibile per 180 giorni"],
      benefitsPill: "Ogni prospettiva in un unico posto",
      benefitsHeading: "Non inseguite le foto dopo il matrimonio.",
      benefitsIntro: "Sostituite foto compresse nelle chat, link sparsi e promemoria con un unico percorso.",
      benefits: [
        { title: "Facile per gli ospiti", description: "Scansionare, scegliere e caricare. Senza download, registrazione o password." },
        { title: "Pronto per la grafica", description: "Scaricate il QR in SVG o PNG per cartelli, segnaposto, menu e schermi." },
        { title: "Momenti spontanei", description: "Raccogliete pista da ballo, selfie ai tavoli e punti di vista degli invitati." },
        { title: "Tutto insieme", description: "Rivedete la galleria, scaricate gli originali e richiedete lo ZIP via email." },
      ],
      clarityPill: "Chiaro fin dall'inizio",
      clarityHeading: "Una galleria condivisa, non un sostituto del fotografo.",
      clarityText: "Il fotografo cattura le immagini essenziali. Guest Mosaic raccoglie i momenti spontanei di ogni tavolo. La galleria non è indicizzata; chi ha link o QR può aprirla.",
      clarityItems: ["Condividete il link solo con gli invitati", "Potete controllare le foto prima di mostrarle", "Scaricate i ricordi prima della fine della conservazione"],
      faqPill: "Prima di iniziare",
      faqHeading: "Domande sul QR per il matrimonio",
      faq: [
        ["Gli invitati devono installare un'app?", "No. Il QR apre la galleria nel browser e non richiede un account."],
        ["Dove mettiamo il codice QR?", "Sul cartello di benvenuto, tavoli, menu, bar, photo booth e vicino alla pista."],
        ["Gli ospiti possono caricare video?", "Sì. Sono inclusi fino a 20 video di 60 secondi, visibili in galleria ma non nel Live Slideshow."],
        ["La galleria è privata?", "Non è indicizzata, ma non è protetta da password per impostazione predefinita."],
        ["Per quanto tempo è disponibile?", "I contenuti restano normalmente disponibili per 180 giorni dopo l'evento."],
      ],
      relatedHeading: "Altri modi per raccogliere foto",
      relatedLink: "Scopri",
    },
    "no-app-sharing": {
      id: "no-app-sharing",
      seoTitle: "Condividere foto di eventi senza app | Guest Mosaic",
      metaDescription: "Gli ospiti scansionano un QR e caricano foto nel browser. Senza app, registrazione o account. Una galleria condivisa a 35 €.",
      navTitle: "Condividere foto senza app",
      eyebrow: "Condivisione foto dal browser",
      title: "Condividete le foto dell'evento senza far installare un'app.",
      description: "Un QR apre il caricamento nel browser. Gli ospiti scelgono le foto, le aggiungono all'evento e tornano a festeggiare.",
      primaryCta: "Crea la galleria — 35 €",
      secondaryCta: "Prova come ospite",
      trust: ["35 € per evento · IVA inclusa", "Nessun account ospite", "Ospiti illimitati"],
      benefitsPill: "Meno attrito",
      benefitsHeading: "Il percorso breve dal rullino alla galleria.",
      benefitsIntro: "Gli ospiti partecipano dal dispositivo che hanno già in mano.",
      benefits: [
        { title: "Nessun app store", description: "La pagina si apre dalla fotocamera o dal link dell'evento." },
        { title: "Nessun account", description: "Niente email, password o registrazione." },
        { title: "Più foto insieme", description: "Selezione multipla e avanzamento visibile per ogni file." },
        { title: "Riprova chiaro", description: "Un trasferimento non riuscito può essere ripetuto." },
      ],
      clarityPill: "Cosa aspettarsi",
      clarityHeading: "Semplice nel browser, trasparente sulla connessione.",
      clarityText: "Guest Mosaic funziona sui browser mobili moderni. L'affidabilità dipende da dispositivo e connessione; i trasferimenti falliti possono essere ripetuti.",
      clarityItems: ["Apertura con QR o link", "Nessuna email o password", "Una galleria per tutto l'evento"],
      faqPill: "Prima dell'evento",
      faqHeading: "Domande sulla condivisione senza app",
      faq: [
        ["Serve un account?", "No. Gli ospiti aprono l'evento e caricano dal browser."],
        ["Possiamo condividere un link?", "Sì. Link e QR aprono la stessa galleria."],
        ["Cosa succede con una connessione debole?", "L'avanzamento è visibile per file e ogni errore può essere riprovato."],
        ["Chi può aprire la galleria?", "Non è indicizzata, ma chi ha link o QR può aprirla."],
      ],
      relatedHeading: "Scegli come condividere le foto",
      relatedLink: "Scopri",
    },
    "event-qr-gallery": {
      id: "event-qr-gallery",
      seoTitle: "Codice QR per condividere foto di eventi | Guest Mosaic",
      metaDescription: "Raccogli foto, brevi video e messaggi in una galleria QR condivisa. Senza app o account. 35 € per evento, IVA inclusa.",
      navTitle: "Codice QR per foto di eventi",
      eyebrow: "Galleria QR per eventi",
      title: "Un codice QR per tutte le foto dell'evento.",
      description: "Gli ospiti scansionano, caricano e sfogliano dal telefono. Tutto confluisce in una galleria condivisa senza abbonamento.",
      primaryCta: "Crea galleria QR — 35 €",
      secondaryCta: "Guarda l'evento demo",
      trust: ["35 € per evento · IVA inclusa", "Ospiti illimitati", "Nessuna app"],
      benefitsPill: "Un evento, una destinazione",
      benefitsHeading: "Partecipare è immediato, raccogliere è automatico.",
      benefitsIntro: "Usate lo stesso QR su cartelli, tavoli, badge e schermi.",
      benefits: [
        { title: "Accesso rapido", description: "Scansiona e carica dal browser senza account." },
        { title: "Più delle foto", description: "Foto, fino a 20 brevi video e messaggi vocali." },
        { title: "Controllo visibilità", description: "Controllate i contributi prima di mostrarli." },
        { title: "Download semplice", description: "Scaricate gli originali o richiedete uno ZIP temporaneo." },
      ],
      clarityPill: "Per ogni occasione",
      clarityHeading: "Dai matrimoni agli eventi aziendali.",
      clarityText: "Lo stesso flusso funziona per feste, compleanni, team building, congressi e fiere.",
      clarityItems: ["Matrimoni e feste private", "Team building ed eventi aziendali", "Congressi e fiere"],
      faqPill: "Pianifica la galleria",
      faqHeading: "Domande sulle gallerie QR",
      faq: [
        ["Quanti ospiti possono partecipare?", "Non c'è un limite di ospiti per evento."],
        ["Possiamo mostrare le foto su uno schermo?", "Sì. Il Live Slideshow mostra le foto idonee e approvate."],
        ["Si può caricare dopo l'evento?", "I caricamenti terminano alla data e ora impostate."],
        ["C'è un abbonamento?", "No. Il prezzo base è 35 € IVA inclusa per evento."],
      ],
      relatedHeading: "Esplora le opzioni per le foto",
      relatedLink: "Scopri",
    },
  },
  fr: {
    "wedding-qr": {
      id: "wedding-qr",
      seoTitle: "QR code pour les photos de mariage | Guest Mosaic",
      metaDescription: "Rassemblez les photos et courtes vidéos des invités dans une galerie partagée. Ils scannent un QR code et envoient depuis le navigateur. 35 €.",
      navTitle: "QR code pour photos de mariage",
      eyebrow: "Partage de photos de mariage par QR code",
      title: "Toutes les photos de vos invités avec un seul QR code.",
      description: "Placez le code sur le panneau d'accueil, les tables ou les faire-part. Les invités envoient photos, courtes vidéos et messages depuis leur téléphone, sans application ni compte.",
      primaryCta: "Créer la galerie — 35 €",
      secondaryCta: "Tester l'envoi comme invité",
      trust: ["35 € par événement · TVA incluse · sans abonnement", "Invités illimités", "Galerie disponible 180 jours"],
      benefitsPill: "Tous les points de vue au même endroit",
      benefitsHeading: "Ne courez plus après les photos du mariage.",
      benefitsIntro: "Remplacez les photos compressées dans les groupes, les liens dispersés et les relances par un seul parcours.",
      benefits: [
        { title: "Simple pour les invités", description: "Scanner, choisir et envoyer. Sans téléchargement, inscription ni mot de passe." },
        { title: "Prêt pour votre papeterie", description: "Téléchargez le QR en SVG ou PNG pour panneaux, menus et marque-places." },
        { title: "Des moments spontanés", description: "Rassemblez la piste de danse, les tables et le regard de vos invités." },
        { title: "Tout réuni ensuite", description: "Consultez la galerie, téléchargez les originaux et demandez le ZIP par e-mail." },
      ],
      clarityPill: "Clair dès le départ",
      clarityHeading: "Une galerie partagée, pas un remplacement du photographe.",
      clarityText: "Votre photographe capture les images essentielles. Guest Mosaic rassemble les instants spontanés de chaque table. La galerie n'est pas indexée ; toute personne ayant le lien ou QR peut l'ouvrir.",
      clarityItems: ["Partagez le lien uniquement avec vos invités", "Vérifiez les photos avant de les afficher", "Téléchargez les souvenirs avant la fin de la conservation"],
      faqPill: "Avant de commencer",
      faqHeading: "Questions sur le QR code de mariage",
      faq: [
        ["Les invités doivent-ils installer une application ?", "Non. Le QR ouvre la galerie dans le navigateur et aucun compte n'est requis."],
        ["Où afficher le QR code ?", "Sur l'accueil, les tables, menus, au bar, près du photobooth et de la piste."],
        ["Les invités peuvent-ils envoyer des vidéos ?", "Oui. Jusqu'à 20 vidéos de 60 secondes sont incluses ; elles ne passent pas dans le Live Slideshow."],
        ["La galerie est-elle privée ?", "Elle n'est pas indexée, mais n'est pas protégée par mot de passe par défaut."],
        ["Combien de temps reste-t-elle disponible ?", "Les contenus sont généralement conservés 180 jours après l'événement."],
      ],
      relatedHeading: "D'autres façons de rassembler les photos",
      relatedLink: "Découvrir",
    },
    "no-app-sharing": {
      id: "no-app-sharing",
      seoTitle: "Partager les photos d'un événement sans application | Guest Mosaic",
      metaDescription: "Les invités scannent un QR et envoient leurs photos dans le navigateur. Sans application, inscription ni compte. Une galerie à 35 €.",
      navTitle: "Partager les photos sans application",
      eyebrow: "Partage de photos depuis le navigateur",
      title: "Partagez les photos sans demander d'installer une application.",
      description: "Un QR code ouvre l'envoi dans le navigateur. Les invités choisissent leurs photos, les ajoutent à l'événement puis retournent à la fête.",
      primaryCta: "Créer la galerie — 35 €",
      secondaryCta: "Tester comme invité",
      trust: ["35 € par événement · TVA incluse", "Aucun compte invité", "Invités illimités"],
      benefitsPill: "Moins de friction",
      benefitsHeading: "Le chemin le plus court de l'appareil à la galerie.",
      benefitsIntro: "Les invités participent depuis le téléphone qu'ils ont déjà en main.",
      benefits: [
        { title: "Sans app store", description: "La page s'ouvre depuis l'appareil photo ou le lien de l'événement." },
        { title: "Sans compte", description: "Aucun e-mail, mot de passe ou formulaire d'inscription." },
        { title: "Plusieurs photos", description: "Sélection multiple et progression visible pour chaque fichier." },
        { title: "Nouvelle tentative", description: "Un transfert échoué peut être relancé clairement." },
      ],
      clarityPill: "À quoi s'attendre",
      clarityHeading: "Simple dans le navigateur, transparent sur la connexion.",
      clarityText: "Guest Mosaic fonctionne sur les navigateurs mobiles modernes. La fiabilité dépend de l'appareil et de la connexion ; les échecs peuvent être relancés.",
      clarityItems: ["Ouverture par QR ou lien", "Sans e-mail ni mot de passe", "Une galerie pour tout l'événement"],
      faqPill: "Avant l'événement",
      faqHeading: "Questions sur le partage sans application",
      faq: [
        ["Faut-il un compte ?", "Non. Les invités ouvrent l'événement et envoient depuis le navigateur."],
        ["Peut-on partager un lien ?", "Oui. Le lien et le QR ouvrent la même galerie."],
        ["Que se passe-t-il avec une mauvaise connexion ?", "La progression est affichée par fichier et chaque échec peut être relancé."],
        ["Qui peut ouvrir la galerie ?", "Elle n'est pas indexée, mais toute personne ayant le lien ou QR peut l'ouvrir."],
      ],
      relatedHeading: "Choisissez la bonne façon de partager",
      relatedLink: "Découvrir",
    },
    "event-qr-gallery": {
      id: "event-qr-gallery",
      seoTitle: "QR code pour partager les photos d'un événement | Guest Mosaic",
      metaDescription: "Rassemblez photos, courtes vidéos et messages dans une galerie QR partagée. Sans application ni compte. 35 € par événement.",
      navTitle: "QR code pour photos d'événement",
      eyebrow: "Galerie QR pour événements",
      title: "Un QR code pour toutes les photos de l'événement.",
      description: "Les invités scannent, envoient et consultent depuis leur téléphone. Tout arrive dans une galerie partagée sans abonnement.",
      primaryCta: "Créer la galerie QR — 35 €",
      secondaryCta: "Voir l'événement démo",
      trust: ["35 € par événement · TVA incluse", "Invités illimités", "Sans application"],
      benefitsPill: "Un événement, une destination",
      benefitsHeading: "Participer est évident, rassembler est automatique.",
      benefitsIntro: "Utilisez le même QR sur les panneaux, tables, badges et écrans.",
      benefits: [
        { title: "Accès rapide", description: "Scannez et envoyez dans le navigateur sans compte." },
        { title: "Plus que des photos", description: "Photos, jusqu'à 20 courtes vidéos et messages vocaux." },
        { title: "Visibilité maîtrisée", description: "Vérifiez les contributions avant de les afficher." },
        { title: "Téléchargement simple", description: "Téléchargez les originaux ou demandez un ZIP temporaire." },
      ],
      clarityPill: "Pour chaque occasion",
      clarityHeading: "Des mariages aux événements d'entreprise.",
      clarityText: "Le même parcours convient aux fêtes, anniversaires, team buildings, conférences et salons.",
      clarityItems: ["Mariages et fêtes privées", "Team buildings et événements d'entreprise", "Conférences et salons"],
      faqPill: "Planifiez la galerie",
      faqHeading: "Questions sur les galeries QR",
      faq: [
        ["Combien d'invités peuvent participer ?", "Il n'y a pas de limite d'invités par événement."],
        ["Peut-on afficher les photos sur un écran ?", "Oui. Le Live Slideshow montre les photos éligibles et approuvées."],
        ["Peut-on envoyer après l'événement ?", "Les envois ferment à la date et l'heure de fin configurées."],
        ["Y a-t-il un abonnement ?", "Non. Le prix de base est de 35 € TVA incluse par événement."],
      ],
      relatedHeading: "Explorez les options de partage",
      relatedLink: "Découvrir",
    },
  },
};
