import type { SolutionPageId, SolutionPageLocale } from "@/lib/i18n/routes";
import { romanceSolutionPages } from "./solution-pages-romance";

type Benefit = { title: string; description: string };

export type SolutionPageContent = {
  id: SolutionPageId;
  seoTitle: string;
  metaDescription: string;
  navTitle: string;
  eyebrow: string;
  title: string;
  description: string;
  primaryCta: string;
  secondaryCta: string;
  trust: readonly string[];
  benefitsPill: string;
  benefitsHeading: string;
  benefitsIntro: string;
  benefits: readonly Benefit[];
  clarityPill: string;
  clarityHeading: string;
  clarityText: string;
  clarityItems: readonly string[];
  faqPill: string;
  faqHeading: string;
  faq: readonly (readonly [string, string])[];
  relatedHeading: string;
  relatedLink: string;
};

const content: Record<SolutionPageLocale, Record<SolutionPageId, SolutionPageContent>> = {
  en: {
    "wedding-qr": {
      id: "wedding-qr",
      seoTitle: "Wedding QR Code for Photos | Guest Mosaic",
      metaDescription: "Collect wedding photos and short videos from your guests in one shared gallery. They scan a QR code and upload in the browser—no app or account. €35 per event.",
      navTitle: "Wedding photo QR code",
      eyebrow: "Wedding photo sharing with a QR code",
      title: "Collect your guests’ wedding photos with one QR code.",
      description: "Place the code on your welcome sign, tables or invitations. Guests scan it and upload photos, short videos and voice messages straight from their phone—no app and no guest account.",
      primaryCta: "Create your wedding gallery — €35",
      secondaryCta: "Try uploading as a guest",
      trust: ["€35 per event · VAT included · no subscription", "Unlimited guests", "Gallery for 180 days after the event"],
      benefitsPill: "One place for every perspective",
      benefitsHeading: "Stop chasing photos after the wedding.",
      benefitsIntro: "Replace compressed group-chat photos, scattered album links and follow-up reminders with one simple contribution flow.",
      benefits: [
        { title: "Easy for guests", description: "Scan, choose photos and upload. No download, sign-up or password to remember." },
        { title: "Ready for your stationery", description: "Download the QR code as SVG or PNG for signs, table cards, menus and screens." },
        { title: "More than posed photos", description: "Collect dance-floor moments, table selfies and memories seen from your guests’ point of view." },
        { title: "Together after the event", description: "Review the gallery, download individual photos and request a ZIP download link by email." },
      ],
      clarityPill: "Clear by design",
      clarityHeading: "A shared gallery, not a replacement for your photographer.",
      clarityText: "Your photographer captures the defining images. Guest Mosaic brings together the candid moments from every table. The gallery is not indexed by search engines; anyone with its event link or QR code can open it.",
      clarityItems: ["Share the link only with the people you want to invite", "Photos can be reviewed before they appear publicly", "Download what you want to keep before the retention period ends"],
      faqPill: "Questions before you start",
      faqHeading: "Wedding photo QR code FAQ",
      faq: [
        ["Do guests need to install an app?", "No. The QR code opens the gallery in their mobile browser, and guests do not need to create an account."],
        ["Where should we display the QR code?", "Use the same code in several visible places: the welcome sign, tables, menus, bar, photo booth and a screen near the dance floor."],
        ["Can guests upload videos too?", "Yes. One event includes up to 20 videos, each up to 60 seconds. Videos appear in the gallery, but not in the Live Slideshow."],
        ["Is the gallery private?", "It is unlisted and not publicly indexed, but it is not password-protected by default. Anyone with the link or QR code can open it."],
        ["How long is the gallery available?", "Media for a new event is generally kept for 180 days after the event ends. Download anything you want to keep before then."],
      ],
      relatedHeading: "Other ways to collect event photos",
      relatedLink: "Explore",
    },
    "no-app-sharing": {
      id: "no-app-sharing",
      seoTitle: "Share Event Photos Without an App | Guest Mosaic",
      metaDescription: "Guests scan a QR code and upload event photos in their browser. No app, registration or guest account—one shared gallery for €35 per event.",
      navTitle: "Photo sharing without an app",
      eyebrow: "Browser-based event photo sharing",
      title: "Share event photos without asking anyone to install an app.",
      description: "One QR code opens the upload flow in the phone’s browser. Guests choose their photos, add them to the event and return to the celebration.",
      primaryCta: "Create an event gallery — €35",
      secondaryCta: "Try it as a guest",
      trust: ["€35 per event · VAT included · no subscription", "No guest account", "Unlimited guests"],
      benefitsPill: "Less friction for guests",
      benefitsHeading: "A shorter path from camera roll to shared gallery.",
      benefitsIntro: "Guests contribute from the device already in their hand, without an app-store detour or a registration form.",
      benefits: [
        { title: "No app-store detour", description: "The upload page opens from the phone camera or a shared event link." },
        { title: "No guest accounts", description: "Guests do not enter an email address, create a password or register." },
        { title: "Several photos at once", description: "Guests can select multiple files and follow the progress of each upload." },
        { title: "A clear retry path", description: "If a transfer fails, the upload flow lets the guest try that file again." },
      ],
      clarityPill: "What to expect",
      clarityHeading: "Simple in the browser, honest about the connection.",
      clarityText: "Guest Mosaic works on modern mobile browsers. Upload reliability still depends on the guest’s device, browser and connection, so failed transfers include a retry path.",
      clarityItems: ["Open by QR code or direct link", "No email or password for guests", "One shared gallery for the whole event"],
      faqPill: "Before your event",
      faqHeading: "No-app photo sharing FAQ",
      faq: [
        ["Do guests need an account?", "No. They open the event in their browser and upload without creating a guest account."],
        ["Can we share a link instead of the QR code?", "Yes. The QR code and the event link open the same gallery, so you can use whichever suits the moment."],
        ["What happens on a poor connection?", "Upload progress is shown per file. If a transfer fails, the guest can retry when the connection improves."],
        ["Who can open the gallery?", "The gallery is not publicly indexed. Anyone with its event link or QR code can open it, so share them only with your intended guests."],
      ],
      relatedHeading: "Choose the right photo-sharing setup",
      relatedLink: "Explore",
    },
    "event-qr-gallery": {
      id: "event-qr-gallery",
      seoTitle: "QR Code for Event Photo Sharing | Guest Mosaic",
      metaDescription: "Collect event photos, short videos and voice messages in one shared QR gallery. No app or guest account. €35 per event, VAT included.",
      navTitle: "Event photo sharing QR code",
      eyebrow: "QR gallery for events",
      title: "One QR code for all the photos from your event.",
      description: "Guests scan, upload and browse from their phone. You get one shared gallery for photos, short videos and voice messages—without a subscription.",
      primaryCta: "Create your QR gallery — €35",
      secondaryCta: "View the demo event",
      trust: ["€35 per event · VAT included · no subscription", "Unlimited guests", "No app for guests"],
      benefitsPill: "One event, one destination",
      benefitsHeading: "Make contributing obvious and collecting automatic.",
      benefitsIntro: "Use the same QR code across signs, tables, badges and screens so every guest knows where their photos belong.",
      benefits: [
        { title: "Quick to join", description: "Scan the code and upload in a mobile browser without creating an account." },
        { title: "More than photos", description: "Collect photos, up to 20 short videos and optional voice messages in the event gallery." },
        { title: "Control visibility", description: "Review contributions and decide which eligible photos are public in the gallery and slideshow." },
        { title: "Easy to take away", description: "Download individual photos or request a secure, time-limited ZIP download link." },
      ],
      clarityPill: "Fits the occasion",
      clarityHeading: "From weddings to company events.",
      clarityText: "The same simple flow works for celebrations, birthdays, team-building events, conferences and trade shows. Adjust the event dates and share one link or QR code.",
      clarityItems: ["Weddings and private celebrations", "Team-building and company events", "Conferences and trade shows"],
      faqPill: "Plan your QR gallery",
      faqHeading: "Event QR gallery FAQ",
      faq: [
        ["How many guests can join?", "The event does not have a per-guest limit."],
        ["Can we show photos on a screen?", "Yes. Open the Live Slideshow on a TV or projector. Eligible, approved photos appear as the gallery grows; videos and voice messages are not shown."],
        ["Can guests upload after the event?", "Uploads close at the end date and time set by the organiser. Set the event window to cover the period in which you want to accept contributions."],
        ["Is there a subscription?", "No. The base price is €35 including VAT per event."],
      ],
      relatedHeading: "Explore event photo-sharing options",
      relatedLink: "Explore",
    },
  },
  de: {
    "wedding-qr": {
      id: "wedding-qr",
      seoTitle: "Hochzeitsfotos per QR-Code sammeln | Guest Mosaic",
      metaDescription: "Sammelt Fotos, kurze Videos und Sprachnachrichten eurer Hochzeitsgäste in einer Galerie – ohne App oder Anmeldung. 35 € pro Event.",
      navTitle: "QR-Code für Hochzeitsfotos",
      eyebrow: "Hochzeitsfotos per QR-Code sammeln",
      title: "Alle Gästefotos eurer Hochzeit. In einer Galerie.",
      description: "Eure Gäste scannen den QR-Code und laden Fotos, kurze Videos und Sprachnachrichten direkt im Browser hoch – ohne App und ohne Anmeldung.",
      primaryCta: "Hochzeitsgalerie erstellen — 35 €",
      secondaryCta: "Gäste-Upload ausprobieren",
      trust: ["35 € pro Event · inkl. MwSt. · kein Abo", "Unbegrenzt viele Gäste", "Galerie 180 Tage nach dem Event verfügbar"],
      benefitsPill: "Alle Perspektiven an einem Ort",
      benefitsHeading: "Nach der Hochzeit keine Fotos mehr zusammensuchen.",
      benefitsIntro: "Ersetzt komprimierte Bilder in Gruppenchats, verstreute Albumlinks und Erinnerungsnachrichten durch einen einfachen Upload.",
      benefits: [
        { title: "Einfach für Gäste", description: "Scannen, Fotos auswählen und hochladen – ohne Download, Registrierung oder Passwort." },
        { title: "Für eure Papeterie", description: "Ladet den QR-Code als SVG oder PNG für Schilder, Tischkarten, Menüs und Bildschirme herunter." },
        { title: "Mehr als gestellte Fotos", description: "Sammelt Tanzflächenmomente, Tisch-Selfies und Erinnerungen aus Sicht eurer Gäste." },
        { title: "Danach zusammen", description: "Sichtet die Galerie, ladet einzelne Fotos herunter oder fordert den ZIP-Downloadlink per E-Mail an." },
      ],
      clarityPill: "Transparent erklärt",
      clarityHeading: "Eine gemeinsame Galerie – kein Ersatz für euren Fotografen.",
      clarityText: "Euer Fotograf hält die wichtigsten Motive fest. Guest Mosaic sammelt die spontanen Momente von jedem Tisch. Die Galerie ist nicht öffentlich indexiert; wer den individuellen Link oder QR-Code hat, kann sie öffnen.",
      clarityItems: ["Teilt Link und QR-Code nur mit euren Gästen", "Fotos können vor der Veröffentlichung geprüft werden", "Ladet Erinnerungen vor Ablauf der Speicherfrist herunter"],
      faqPill: "Fragen vor dem Start",
      faqHeading: "FAQ zum QR-Code für Hochzeitsfotos",
      faq: [
        ["Müssen Gäste eine App installieren?", "Nein. Der QR-Code öffnet die Galerie im mobilen Browser. Ein Gastkonto ist nicht nötig."],
        ["Wo sollten wir den QR-Code zeigen?", "Nutzt denselben Code an mehreren gut sichtbaren Stellen: am Willkommensschild, auf Tischen, Menüs, an der Bar oder nahe der Tanzfläche."],
        ["Können Gäste auch Videos hochladen?", "Ja. Ein Event enthält bis zu 20 Videos mit jeweils bis zu 60 Sekunden. Videos erscheinen in der Galerie, aber nicht in der Live-Diashow."],
        ["Ist die Galerie privat?", "Sie ist nicht öffentlich indexiert, aber standardmäßig nicht passwortgeschützt. Wer den Link oder QR-Code hat, kann sie öffnen."],
        ["Wie lange ist die Galerie verfügbar?", "Medien eines neuen Events werden in der Regel 180 Tage nach dem Ende des Events aufbewahrt. Ladet vorher alles herunter, was ihr behalten möchtet."],
      ],
      relatedHeading: "Weitere Wege, Eventfotos zu sammeln",
      relatedLink: "Ansehen",
    },
    "no-app-sharing": {
      id: "no-app-sharing",
      seoTitle: "Eventfotos ohne App teilen | Guest Mosaic",
      metaDescription: "Gäste scannen einen QR-Code und laden Eventfotos direkt im Browser hoch. Ohne App, Registrierung oder Gastkonto. 35 € pro Event.",
      navTitle: "Eventfotos ohne App teilen",
      eyebrow: "Foto-Sharing per QR-Code",
      title: "Eventfotos sammeln und teilen – ohne App für Ihre Gäste.",
      description: "Ihre Gäste scannen den QR-Code, wählen Fotos oder kurze Videos aus und laden sie direkt im Browser hoch. Alles landet in einer gemeinsamen Galerie.",
      primaryCta: "QR-Galerie erstellen — 35 €",
      secondaryCta: "Als Gast ausprobieren",
      trust: ["35 € pro Event · inkl. MwSt. · kein Abo", "Kein Gastkonto", "Unbegrenzt viele Gäste"],
      benefitsPill: "Weniger Hürden",
      benefitsHeading: "Der kurze Weg von der Kamera in die Eventgalerie.",
      benefitsIntro: "Gäste nutzen das Smartphone, das sie bereits in der Hand haben – ohne Umweg über den App Store oder ein Registrierungsformular.",
      benefits: [
        { title: "Keine App-Installation", description: "Die Uploadseite öffnet sich über die Handykamera oder den geteilten Eventlink." },
        { title: "Keine Gastkonten", description: "Gäste geben keine E-Mail-Adresse ein und erstellen weder Passwort noch Konto." },
        { title: "Mehrere Fotos auf einmal", description: "Gäste wählen mehrere Dateien aus und sehen den Fortschritt jedes Uploads." },
        { title: "Erneut versuchen", description: "Schlägt eine Übertragung fehl, kann die einzelne Datei erneut hochgeladen werden." },
      ],
      clarityPill: "Was Sie erwarten können",
      clarityHeading: "Einfach im Browser – abhängig von der Verbindung.",
      clarityText: "Guest Mosaic funktioniert in modernen mobilen Browsern. Die Zuverlässigkeit hängt weiterhin von Gerät, Browser und Verbindung des Gastes ab; fehlgeschlagene Uploads können wiederholt werden.",
      clarityItems: ["Per QR-Code oder Direktlink öffnen", "Keine E-Mail und kein Passwort für Gäste", "Eine gemeinsame Galerie für das ganze Event"],
      faqPill: "Vor Ihrem Event",
      faqHeading: "FAQ zum Foto-Sharing ohne App",
      faq: [
        ["Brauchen Gäste ein Konto?", "Nein. Sie öffnen das Event im Browser und laden ohne Gastkonto hoch."],
        ["Können wir statt des QR-Codes einen Link teilen?", "Ja. QR-Code und Eventlink öffnen dieselbe Galerie."],
        ["Was passiert bei einer schlechten Verbindung?", "Der Fortschritt wird pro Datei angezeigt. Schlägt die Übertragung fehl, kann der Gast sie später erneut versuchen."],
        ["Wer kann die Galerie öffnen?", "Die Galerie ist nicht öffentlich indexiert. Wer den Eventlink oder QR-Code hat, kann sie öffnen; teilen Sie beides daher nur mit den gewünschten Gästen."],
      ],
      relatedHeading: "Das passende Foto-Sharing wählen",
      relatedLink: "Ansehen",
    },
    "event-qr-gallery": {
      id: "event-qr-gallery",
      seoTitle: "QR-Fotogalerie für Events | Guest Mosaic",
      metaDescription: "Sammeln Sie Eventfotos, kurze Videos und Sprachnachrichten in einer gemeinsamen QR-Galerie. Ohne App oder Gastkonto. 35 € pro Event.",
      navTitle: "QR-Fotogalerie für Events",
      eyebrow: "QR-Fotogalerie für Events",
      title: "Alle Eventfotos über einen QR-Code sammeln.",
      description: "Gäste scannen den QR-Code und laden Fotos, kurze Videos und Sprachnachrichten direkt im Browser hoch. Alles kommt in einer gemeinsamen Galerie zusammen.",
      primaryCta: "QR-Galerie erstellen — 35 €",
      secondaryCta: "Demo-Event ansehen",
      trust: ["35 € pro Event · inkl. MwSt. · kein Abo", "Unbegrenzt viele Gäste", "Keine App für Gäste"],
      benefitsPill: "Ein Event, ein Ziel",
      benefitsHeading: "Mitmachen leicht machen, Medien automatisch sammeln.",
      benefitsIntro: "Verwenden Sie denselben QR-Code auf Schildern, Tischen, Namensschildern und Bildschirmen, damit jeder Gast weiß, wohin seine Fotos gehören.",
      benefits: [
        { title: "Schnell dabei", description: "QR-Code scannen und im mobilen Browser hochladen – ohne Gastkonto." },
        { title: "Mehr als Fotos", description: "Sammeln Sie Fotos, bis zu 20 kurze Videos und optionale Sprachnachrichten." },
        { title: "Sichtbarkeit steuern", description: "Prüfen Sie Beiträge und bestimmen Sie, welche geeigneten Fotos öffentlich erscheinen." },
        { title: "Einfach mitnehmen", description: "Laden Sie einzelne Fotos herunter oder fordern Sie einen sicheren, zeitlich begrenzten ZIP-Link an." },
      ],
      clarityPill: "Für viele Anlässe",
      clarityHeading: "Von Hochzeiten bis zu Firmenevents.",
      clarityText: "Der gleiche einfache Ablauf funktioniert für Feiern, Geburtstage, Teambuildings, Konferenzen und Messen. Legen Sie den Eventzeitraum fest und teilen Sie einen Link oder QR-Code.",
      clarityItems: ["Hochzeiten und private Feiern", "Teambuildings und Firmenevents", "Konferenzen und Messen"],
      faqPill: "QR-Galerie planen",
      faqHeading: "FAQ zur Event-QR-Galerie",
      faq: [
        ["Wie viele Gäste können teilnehmen?", "Für ein Event gibt es kein Limit pro Gast."],
        ["Können wir Fotos auf einem Bildschirm zeigen?", "Ja. Öffnen Sie die Live-Diashow auf einem TV oder Beamer. Geeignete, freigegebene Fotos erscheinen fortlaufend; Videos und Sprachnachrichten werden nicht gezeigt."],
        ["Können Gäste nach dem Event hochladen?", "Uploads schließen zum vom Organisator festgelegten Enddatum und -zeitpunkt. Planen Sie den Eventzeitraum entsprechend."],
        ["Gibt es ein Abonnement?", "Nein. Der Grundpreis beträgt 35 € inklusive Mehrwertsteuer pro Event."],
      ],
      relatedHeading: "Weitere Optionen für Eventfotos",
      relatedLink: "Ansehen",
    },
  },
  nl: {
    "wedding-qr": {
      id: "wedding-qr",
      seoTitle: "Trouwfoto’s verzamelen via QR-code | Guest Mosaic",
      metaDescription: "Verzamel foto’s, korte video’s en spraakberichten van jullie gasten in één galerij. Zonder app of account. € 35 per evenement.",
      navTitle: "QR-code voor trouwfoto’s",
      eyebrow: "Trouwfoto’s verzamelen via QR-code",
      title: "Alle foto’s van jullie bruiloft. In één gedeelde galerij.",
      description: "Gasten scannen de QR-code en uploaden foto’s, korte video’s en spraakberichten rechtstreeks in hun browser – zonder app of account.",
      primaryCta: "Maak jullie trouwgalerij — € 35",
      secondaryCta: "Probeer de upload als gast",
      trust: ["€ 35 per evenement · inclusief btw · geen abonnement", "Onbeperkt aantal gasten", "Galerij 180 dagen na het evenement beschikbaar"],
      benefitsPill: "Elk perspectief op één plek",
      benefitsHeading: "Na de bruiloft niet meer achter foto’s aan.",
      benefitsIntro: "Vervang gecomprimeerde WhatsApp-foto’s, losse albumlinks en herinneringsberichten door één eenvoudige uploadroute.",
      benefits: [
        { title: "Makkelijk voor gasten", description: "Scannen, foto’s kiezen en uploaden. Geen download, registratie of wachtwoord." },
        { title: "Klaar voor jullie drukwerk", description: "Download de QR-code als SVG of PNG voor borden, tafelkaartjes, menu’s en schermen." },
        { title: "Meer dan geposeerde foto’s", description: "Verzamel dansvloermomenten, tafelselfies en herinneringen vanuit het perspectief van jullie gasten." },
        { title: "Na afloop bij elkaar", description: "Bekijk de galerij, download losse foto’s of vraag de ZIP-downloadlink per e-mail aan." },
      ],
      clarityPill: "Duidelijk uitgelegd",
      clarityHeading: "Een gedeelde galerij, geen vervanging voor jullie fotograaf.",
      clarityText: "Jullie fotograaf legt de belangrijkste beelden vast. Guest Mosaic verzamelt de spontane momenten van elke tafel. De galerij wordt niet openbaar geïndexeerd; iedereen met de unieke link of QR-code kan haar openen.",
      clarityItems: ["Deel de link en QR-code alleen met jullie gasten", "Foto’s kunnen vóór publicatie worden beoordeeld", "Download herinneringen voordat de bewaartermijn afloopt"],
      faqPill: "Vragen voor jullie beginnen",
      faqHeading: "Veelgestelde vragen over de QR-code voor trouwfoto’s",
      faq: [
        ["Moeten gasten een app installeren?", "Nee. De QR-code opent de galerij in hun mobiele browser en gasten hoeven geen account te maken."],
        ["Waar kunnen we de QR-code tonen?", "Gebruik dezelfde code op meerdere zichtbare plekken: het welkomstbord, de tafels, menu’s, de bar of bij de dansvloer."],
        ["Kunnen gasten ook video’s uploaden?", "Ja. Eén evenement bevat maximaal 20 video’s van elk maximaal 60 seconden. Video’s staan in de galerij, maar niet in de Live Slideshow."],
        ["Is de galerij privé?", "Ze wordt niet openbaar geïndexeerd, maar is standaard niet met een wachtwoord beveiligd. Iedereen met de link of QR-code kan haar openen."],
        ["Hoelang blijft de galerij beschikbaar?", "Media van een nieuw evenement worden doorgaans 180 dagen na afloop bewaard. Download vóór die tijd wat jullie willen bewaren."],
      ],
      relatedHeading: "Andere manieren om evenementfoto’s te verzamelen",
      relatedLink: "Bekijken",
    },
    "no-app-sharing": {
      id: "no-app-sharing",
      seoTitle: "Evenementfoto’s delen zonder app | Guest Mosaic",
      metaDescription: "Gasten scannen een QR-code en uploaden evenementfoto’s in hun browser. Zonder app, registratie of gastenaccount. € 35 per evenement.",
      navTitle: "Foto’s delen zonder app",
      eyebrow: "Foto’s delen via QR-code",
      title: "Evenementfoto’s verzamelen en delen. Zonder app.",
      description: "Gasten scannen de QR-code, kiezen foto’s of korte video’s en uploaden ze rechtstreeks in hun browser. Alles komt samen in één gedeelde galerij.",
      primaryCta: "Maak een QR-galerij — € 35",
      secondaryCta: "Probeer het als gast",
      trust: ["€ 35 per evenement · inclusief btw · geen abonnement", "Geen gastenaccount", "Onbeperkt aantal gasten"],
      benefitsPill: "Minder stappen voor gasten",
      benefitsHeading: "De korte route van camerarol naar gedeelde galerij.",
      benefitsIntro: "Gasten gebruiken de telefoon die ze al in hun hand hebben, zonder omweg langs een appstore of registratieformulier.",
      benefits: [
        { title: "Geen appstore", description: "De uploadpagina opent via de telefooncamera of een gedeelde evenementlink." },
        { title: "Geen gastenaccounts", description: "Gasten vullen geen e-mailadres in en maken geen wachtwoord of account aan." },
        { title: "Meerdere foto’s tegelijk", description: "Gasten selecteren meerdere bestanden en volgen de voortgang per upload." },
        { title: "Duidelijk opnieuw proberen", description: "Mislukt een overdracht, dan kan de gast dat bestand opnieuw uploaden." },
      ],
      clarityPill: "Wat je kunt verwachten",
      clarityHeading: "Eenvoudig in de browser, afhankelijk van de verbinding.",
      clarityText: "Guest Mosaic werkt in moderne mobiele browsers. De betrouwbaarheid blijft afhankelijk van het apparaat, de browser en de verbinding van de gast; een mislukte upload kan opnieuw worden geprobeerd.",
      clarityItems: ["Openen via QR-code of directe link", "Geen e-mail of wachtwoord voor gasten", "Eén gedeelde galerij voor het hele evenement"],
      faqPill: "Voor je evenement",
      faqHeading: "Veelgestelde vragen over foto’s delen zonder app",
      faq: [
        ["Hebben gasten een account nodig?", "Nee. Ze openen het evenement in hun browser en uploaden zonder gastenaccount."],
        ["Kunnen we een link delen in plaats van de QR-code?", "Ja. De QR-code en de evenementlink openen dezelfde galerij."],
        ["Wat gebeurt er bij een slechte verbinding?", "De voortgang wordt per bestand getoond. Mislukt de overdracht, dan kan de gast het later opnieuw proberen."],
        ["Wie kan de galerij openen?", "De galerij wordt niet openbaar geïndexeerd. Iedereen met de evenementlink of QR-code kan haar openen, dus deel die alleen met de bedoelde gasten."],
      ],
      relatedHeading: "Kies de juiste manier om foto’s te delen",
      relatedLink: "Bekijken",
    },
    "event-qr-gallery": {
      id: "event-qr-gallery",
      seoTitle: "QR-fotogalerij voor evenementen | Guest Mosaic",
      metaDescription: "Verzamel evenementfoto’s, korte video’s en spraakberichten in één gedeelde QR-galerij. Zonder app of gastenaccount. € 35 per evenement.",
      navTitle: "QR-fotogalerij voor evenementen",
      eyebrow: "QR-fotogalerij voor evenementen",
      title: "Verzamel alle evenementfoto’s met één QR-code.",
      description: "Gasten scannen de QR-code en uploaden foto’s, korte video’s en spraakberichten rechtstreeks in hun browser. Alles komt samen in één gedeelde galerij.",
      primaryCta: "Maak een QR-galerij — € 35",
      secondaryCta: "Bekijk het demo-evenement",
      trust: ["€ 35 per evenement · inclusief btw · geen abonnement", "Onbeperkt aantal gasten", "Geen app voor gasten"],
      benefitsPill: "Eén evenement, één bestemming",
      benefitsHeading: "Meedoen vanzelfsprekend, verzamelen automatisch.",
      benefitsIntro: "Gebruik dezelfde QR-code op borden, tafels, badges en schermen, zodat iedere gast weet waar de foto’s thuishoren.",
      benefits: [
        { title: "Snel meedoen", description: "Scan de code en upload in een mobiele browser zonder gastenaccount." },
        { title: "Meer dan foto’s", description: "Verzamel foto’s, maximaal 20 korte video’s en optionele spraakberichten." },
        { title: "Zichtbaarheid beheren", description: "Beoordeel bijdragen en bepaal welke geschikte foto’s openbaar verschijnen." },
        { title: "Makkelijk meenemen", description: "Download losse foto’s of vraag een beveiligde, tijdelijke ZIP-downloadlink aan." },
      ],
      clarityPill: "Voor elke gelegenheid",
      clarityHeading: "Van bruiloft tot zakelijk evenement.",
      clarityText: "Dezelfde eenvoudige werkwijze past bij feesten, verjaardagen, teamuitjes, congressen en beurzen. Stel de evenementperiode in en deel één link of QR-code.",
      clarityItems: ["Bruiloften en privéfeesten", "Teamuitjes en zakelijke evenementen", "Congressen en beurzen"],
      faqPill: "Plan je QR-galerij",
      faqHeading: "Veelgestelde vragen over de QR-galerij",
      faq: [
        ["Hoeveel gasten kunnen meedoen?", "Voor een evenement geldt geen limiet per gast."],
        ["Kunnen we foto’s op een scherm tonen?", "Ja. Open de Live Slideshow op een tv of beamer. Geschikte, goedgekeurde foto’s verschijnen terwijl de galerij groeit; video’s en spraakberichten worden niet getoond."],
        ["Kunnen gasten na het evenement uploaden?", "Uploads sluiten op de einddatum en -tijd die de organisator instelt. Kies een evenementperiode waarin je bijdragen wilt ontvangen."],
        ["Is er een abonnement?", "Nee. De basisprijs is € 35 inclusief btw per evenement."],
      ],
      relatedHeading: "Ontdek opties voor evenementfoto’s",
      relatedLink: "Bekijken",
    },
  },
  ...romanceSolutionPages,
};

export function getSolutionPage(id: SolutionPageId, locale: SolutionPageLocale): SolutionPageContent {
  return content[locale][id];
}
