import type { EventUseCase } from "./use-cases";

export const eventUseCaseGroupsNl = ["Privé-evenementen", "Zakelijke evenementen"] as const;

export const eventUseCasesNl = [
  { slug: "poroke", navTitle: "Bruiloften", navDescription: "Elk spontaan moment van jullie dag.", group: "Privé-evenementen", eyebrow: "QR-galerij voor bruiloften", title: "De trouwfoto's van al je gasten in één galerij.", description: "Gasten scannen een QR-code en voegen zonder app de momenten toe die je fotograaf misschien miste. Na de bruiloft download je alle herinneringen op één plek.", highlights: ["QR-code voor uitnodigingen, menu's en tafelkaartjes", "Eenvoudig uploaden zonder registratie van gasten", "Live slideshow tijdens het hele feest", "Eén ZIP met alle foto's na afloop"], scenarios: ["burgerlijk huwelijk", "trouwfeest", "vrijgezellenfeest", "trouwdag"], faq: [["Vervangt Guest Mosaic een trouwfotograaf?", "Nee. De professionele fotograaf legt de belangrijkste beelden vast; de galerij verzamelt de spontane momenten vanuit het perspectief van je gasten."], ["Waar kunnen we de QR-code plaatsen?", "Op uitnodigingen, het welkomstbord, tafelkaartjes, het menu of een scherm. Meestal verzamel je meer foto's als de code op meerdere plekken zichtbaar is."]] },
  { slug: "rojstni-dnevi", navTitle: "Verjaardagen", navDescription: "Van het eerste kaarsje tot de mijlpalen.", group: "Privé-evenementen", eyebrow: "QR-galerij voor verjaardagen", title: "Het hele feest in ieders herinnering.", description: "Geef je gasten één QR-code in plaats van foto's uit groepschats bij elkaar te zoeken. Iedereen voegt zijn favoriete momenten toe en jij krijgt het volledige verhaal van het feest.", highlights: ["Eén link voor elke generatie", "Geen app, wachtwoorden of accounts", "Reacties en wensen bij de foto's", "Een galerij tijdens en na het feest"], scenarios: ["kinderfeestje", "18e verjaardag", "mijlpaalverjaardag", "verrassingsfeest"], faq: [["Is het eenvoudig genoeg voor oudere gasten?", "Ja. Een gast opent de camera, scant de QR-code en kiest de foto's rechtstreeks in de browser."], ["Kunnen gasten de volgende dag nog foto's toevoegen?", "Ja. De QR-code en de link blijven beschikbaar zolang de galerij actief is."]] },
  { slug: "praznovanja", navTitle: "Feesten", navDescription: "Jubilea, babyshowers en samenkomsten.", group: "Privé-evenementen", eyebrow: "QR-galerij voor feesten", title: "Elk feest verdient een gedeeld album.", description: "Van een familiereünie tot een babyshower: Guest Mosaic verzamelt ieders foto's zonder ingewikkelde mappen, apps of herinneringsberichtjes.", highlights: ["Werkt voor intieme samenkomsten en grote feesten", "Privé, niet-geïndexeerde galerijlink", "Controle over de zichtbaarheid van elke foto", "Alle herinneringen klaar voor één download"], scenarios: ["babyshower", "jubileum", "familiereünie", "diploma-uitreiking"], faq: [["Voor welke feesten is de galerij geschikt?", "Voor bijna elk evenement waar meerdere gasten foto's maken: jubilea, familiereünies, babyshowers, diploma-uitreikingen en andere feesten."], ["Is de galerij openbaar?", "Nee. Hij wordt standaard niet geïndexeerd en is alleen bereikbaar via een niet te raden link of QR-code."]] },
  { slug: "team-building", navTitle: "Teambuildings", navDescription: "Het gezamenlijke verhaal van je team, live vastgelegd.", group: "Zakelijke evenementen", eyebrow: "QR-galerij voor teambuildings", title: "Laat je team de beste momenten van de dag vastleggen.", description: "Deelnemers bouwen de galerij samen op met hun telefoon. Foto's van activiteiten, successen en momenten achter de schermen worden meteen verzameld om intern te delen.", highlights: ["Snelle toegang voor iedereen via één QR-code", "Live slideshow voor de finale of de borrel", "Beheerderscontrole over de zichtbare foto's", "ZIP voor interne communicatie en archief"], scenarios: ["sportactiviteiten", "workshops", "teamuitjes", "bedrijfsfeesten"], faq: [["Kunnen we de galerij tijdens het evenement op een scherm tonen?", "Ja. Open de live slideshow op een computer die is aangesloten op een tv of beamer."], ["Wie bepaalt welke foto's zichtbaar zijn?", "De organisator kan de galerij doornemen en de zichtbaarheid van losse foto's beheren in het beheerportaal."]] },
  { slug: "poslovni-dogodki", navTitle: "Zakelijke evenementen", navDescription: "Bijeenkomsten, lanceringen en presentaties.", group: "Zakelijke evenementen", eyebrow: "QR-galerij voor zakelijke evenementen", title: "Content van deelnemers verzamelen zonder achter kanalen aan te jagen.", description: "Bij een lancering, opening of pop-up leveren deelnemers foto's aan via een QR-code. De organisator krijgt een geordende stroom van echte momenten voor terugblikken en intern gebruik.", highlights: ["Geen app-installatie voor bezoekers", "QR-code op badges, tafels of schermen", "Zichtbaarheidsinstellingen voor een passende publieke weergave", "Centrale download na afloop"], scenarios: ["productlancering", "opening", "pop-upevenement", "zakelijke bijeenkomst"], faq: [["Kan de QR-code op bestaande evenementmaterialen?", "Ja. Download hem als SVG of PNG en zet hem op badges, posters, schermen of drukwerk."], ["Kunnen we content modereren voordat die verschijnt?", "Ja. De organisator beheert de zichtbaarheid van de galerij en van losse foto's in het beheerportaal."]] },
  { slug: "konference-in-sejmi", navTitle: "Congressen en beurzen", navDescription: "Meer perspectieven op programma, mensen en sfeer.", group: "Zakelijke evenementen", eyebrow: "QR-galerij voor congressen en beurzen", title: "De sfeer van het evenement door de ogen van je deelnemers.", description: "Plaats de QR-code bij het podium, op de stand of op badges. Bezoekers dragen foto's bij van lezingen, netwerkmomenten en de locatie aan één beheerde galerij.", highlights: ["Eén ingang voor verschillende onderdelen van het evenement", "Live slideshow voor podium, foyer of stand", "Beoordeling en fotobeheer voor de beheerder", "Geordend archief voor de terugblik"], scenarios: ["congres", "vakbeurs", "conferentie", "netwerkevenement"], faq: [["Waar werkt de QR-code op een congres het best?", "Op badges, in het programma, op de openings- en slotdia's, bij ingangen en in netwerkruimtes."], ["Werkt het ook voor een meerdaags evenement?", "Ja. Stel de evenementdata in bij de bestelling en gebruik dezelfde link gedurende het hele programma."]] },
] as const satisfies readonly EventUseCase[];
